category_dict = {
                    'The Number Pi': [
                                        'pi_memorization',
                                    ],
                    'Combinations': [
                                        '3_block_towers',
                                        'break_it_up!',
                                        'Button-up_some_more',
                                        'Cuisenaire_counting',
                                        'Fruity_pairs',
                                        'Ice_cream',
                                        'Ice_cream_scoop',
                                        'Making_shapes',
                                        'Sort_the_street',
                                        'three_ball_line_up',
                                    ],
                    'Place Value': [
                                        '6_beads',
                                        'what_number?',
                                    ],
                    'Riddle': [
                                        'Brothers_and_sisters',
                                        'Caesar_cipher',
                                        'How_old_am_i?',
                                        'In_the_money',
                                        'Repairing_a_chain',
                                        'Scale_test',
                                        'Striking_midnight',
                                        'The_restless_fly',
                                        'Three_moves',
                                        'which_scripts?',
                                    ],
                    'Problem Solving': [
                                        '30_cubes',
                                        '50_coins',
                                        "Amy's_dominoes",
                                        'Birthday_cake_candles',
                                        'Brush_loads',
                                        'Butterfly_flowers',
                                        'Changing_50_cents',
                                        'Curious_number',
                                        'Dice_in_a_corner',
                                        'Digit_addition',
                                        'domino_square_(easy)',
                                        'domino_square_(hard)',
                                        'Fitted',
                                        'Forgot_the_numbers',
                                        'Four-digit_targets',
                                        'Friday_13th',
                                        'Leo_the_rabbit',
                                        'Make_37',
                                        'Maximizing_area',
                                        'Money_bags',
                                        'Pairs_of_numbers',
                                        'Pentagon_sums',
                                        'Possible_pieces',
                                        'Ribbon_squares',
                                        'Satisfying_four_statements',
                                        'Sealed_solution',
                                        'Seven_flipped',
                                        'Skeleton_shapes',
                                        'Taxi_cab',
                                        'Teddy_town',
                                        'That_number_square!',
                                        'Toothpick_geometry',
                                        'Twenty_divided_into_six',
                                        'wimbledon_matches',
                                    ],
                    'Tangrams': [
                                        'Square_tangram',
                                        'Tangram_tangle',
                                        'tangrams',
                                    ],
                    'Number Arrangements': [
                                        'Calendar_sorting',
                                        'Build_it_up',
                                        'Find_the_difference',
                                        'Hundred_square_poster',
                                        'Magic_crosses',
                                        'Magic_vs',
                                        'Maze_100',
                                        'Number_differences',
                                        'Number_sandwiches',
                                        'One_big_triangle',
                                        'Reach_100',
                                        'Ring_a_ring_of_numbers',
                                        'The_tall_tower',
                                        'Triangle_sums',
                                        'Two-digit_targets',
                                        "What's_in_a_name?",
                                        'Evening_out',
                                        'evening_out_ladybird',
                                    ],
                    
                    'Tricky Patterns': [
                                        'Diminishing_returns',
                                        'Grains_of_rice',
                                        'Looking_at_lego',
                                        'Painted_cube',
                                        'Picture_story',
                                        'Route_to_infinity',
                                        'The_amazing_splitting_plant',
                                        'The_deca_tree',
                                        "what's_happening",
                                    ],
                    'Graphing': [
                                        'A_cartesian_puzzle',
                                    ],
                    'Logic and Proof': [
                                        'A_fork_in_the_road',
                                        'Asn_numbers',
                                        'asn_numbers_(medium)',
                                        'Asn_shapes',
                                        'asn_shapes_(medium)',
                                        'Chessboard_squares',
                                        "Heron's_formula",
                                        'Odd_times_even',
                                        'Paper_folding',
                                        'Seven_bridges',
                                        'Sorting_logic_blocks',
                                        'two_numbers_under_the_microscope',
                                    ],
                    'Equation Manipulation': [
                                        'Highest_and_lowest',
                                        'Operators_puzzle',
                                        'pemdas_puzzle',
                                    ],
                    'Clue Puzzles': [
                                        'A_mixed-up_clock',
                                        'Cookie_decorations',
                                        'Eggs_in_baskets',
                                        "Einstein's_riddle",
                                        'Fifteen_cards',
                                        'Letter_logic',
                                        'Lunch_room_logic',
                                        'Number_detective',
                                        'Number_riddle',
                                        'Shape_riddle',
                                        'Swimmer_logic',
                                        'toothpick_clues',
                                    ],
                    'Shape Visualization': [
                                        'A_puzzling_cube',
                                        'Cut_nets',
                                        'Four_colors',
                                        'Four_triangles_puzzle',
                                        'Hex',
                                        'Marbles_in_a_box',
                                        'Nine_colors',
                                        'Overlaps',
                                        'Shadow_play',
                                        'Start_cube_drilling',
                                        'Three_squares',
                                        'crazy_cut',
                                    ],
                    'Visual Fractions': [
                                        'Rod_fractions',
                                        'fraction_lengths',
                                        'rod_ratios',
                                    ],
                    'Geometry Fractions': [
                                        'Kite_in_a_square',
                                        'area_fractions',
                                    ],
                    'Ratio Reasoning': [
                                        'A_bowl_of_fruit',
                                    ],
                    'Open Exploration': [
                                        'Egyptian_rope',
                                        'Healthy_snack_shop',
                                        "I'm_eight",
                                        'Ladybird_count',
                                        'Name_that_triangle',
                                        'Number_lines_in_disguise',
                                        'Paper_halving',
                                        'Repeating_patterns',
                                        'school_fair_necklaces',
                                        'Square_patterns',
                                        'Square_subtraction',
                                        'Sums_investigation',
                                        'Swimming_pool_tiles',
                                        'Take_three_numbers',
                                        'Trap_the_zoid',
                                        'Triangle_transformation',
                                        'two_primes_make_one_square',
                                    ],
                    'Factors and Multiples': [
                                        'Counting_cogs',
                                        'Factor-multiple_chains',
                                        'Groups_of_pennies',
                                        'Growing_garlic',
                                        'Ip_dip',
                                        'Ladybirds_in_the_garden',
                                        'Lots_of_lollies',
                                        'Making_sticks',
                                        'Numbers_and_shapes',
                                        'Robot_stepper',
                                        'Tiling',
                                        "What's_in_the_box?",
                                        'Remainders_riddle',
                                    ],
                    'Systems Riddle': [
                                        'Counting_legs',
                                        'Heads_and_feet',
                                        'Noah',
                                        'Starfish_spotting',
                                        'zios_and_zepts',
                                    ],
                    'Systems Picture': [
                                        'Linear_systems',
                                        'Pet_scale',
                                        'systems_grid',
                                    ],
                    'Arithmetic Puzzle': [
                                        'Addition_shuffle',
                                        'Addition_swap',
                                        'Algorithm_clues_addition',
                                        'Multiplication_swap',
                                        'Shape_times_shape',
                                        'super_shapes',
                                    ],
                    'Area Puzzle': [
                                        'Area_calculation',
                                        'Area_comparison',
                                        'Circular_area',
                                        'Halving',
                                    ],
                    'Number Sequences': [
                                        'neighborly_addition',
                                        'Next-door_numbers',
                                        'Consecutive_numbers',
                                        'Odd_summation',
                                        'three_neighbors',
                                    ],
                    'Discussion': [
                                        'Choosing_quadrilaterals',
                                        'Choosing_triangles',
                                        'Coloring_triangles',
                                        'Data_duos',
                                        'Little_man',
                                        'Matching_triangles',
                                        'Mental_arithmetic',
                                        'Multiplying_methods',
                                        'Mystery_matrix',
                                        'Number_rule',
                                        'Numbers_wodb',
                                        'Pictures_wodb',
                                        'Ranking_addition',
                                        'Ranking_multiplication',
                                        'Rearranged_rectangle',
                                        'Same_length_trains',
                                        'Sizing_them_up',
                                        'Sweetie_box',
                                        't/f_number_sentences',
                                        'Tables_teaser',
                                        'Wallpaper',
                                        'what_do_you_see_here?',
                                        'pi_memorization',
                                    ],
                    'Pegboards': [
                                        'happy_halving',
                                        'Inside_triangles',
                                        'Nine-pin_triangles',
                                        'peg_board_challenge',
                                    ],
                    'Raw Data': [
                                        'data_table',
                                    ],
                    '1-2-3 Patterns': [
                                        'Circle_fever',
                                        'Cuisenaire_squares',
                                        'Holes',
                                        'Squares_to_stairs',
                                        'Squares_upon_squares',
                                        'Sticky_triangles',
                                        'visual_patterns',
                                    ],
                    'Visual Algebra': [
                                        'Coin_scale',
                                        'Honey_scale',
                                        'shape_scale',
                                    ],
                    'Counting': [
                                        'How_many',
                                        'how_would_we_count?',
                                    ],
                }
                
standards_dict = {

"Next-door_numbers": "1.OA.A.1, 1.OA.A.2, 1.OA.B.3, 1.OA.B.4, 1.OA.C.5, 1.OA.C.6, 2.OA.A.1, 2.OA.B.2",
"Triangle_sums": "1.OA.A.1, 1.OA.A.2, 1.OA.B.3, 1.OA.B.4, 1.OA.C.5, 1.OA.C.6, 2.OA.A.1, 2.OA.B.2",
"Butterfly_flowers": "1.OA.A.1, 1.OA.A.2, 1.OA.B.3, 1.OA.B.4, 1.OA.C.5, 1.OA.C.6, 2.OA.A.1, 2.OA.B.2",
"Maze_100": "1.OA.A.1, 1.OA.A.2, 1.OA.B.3, 1.OA.B.4, 1.OA.C.5, 1.OA.C.6, 2.OA.A.1, 2.OA.B.2",
"t/f_number_sentences": "1.OA.D.7",
"Find_the_difference": "1.OA.D.8",
"How_would_we_count?": "1.NBT.A.1",
"6_beads": "1.NBT.B.2, 1.NBT.B.3, 1.NBT.C.4, 2.NBT.A.1, 2.NBT.A.4",
"What_number?": "1.NBT.B.2, 1.NBT.B.3, 1.NBT.C.4, 2.NBT.A.1, 2.NBT.A.4, 2.NBT.B.5",
"Hundred_square_poster": "1.NBT.C.5, 1.NBT.C.6, 2.NBT.A.2, 2.NBT.A.3, 2.NBT.B.5",
"Same_length_trains": "1.MD.A.1, 1.MD.A.2, 2.MD.A.1, 2.MD.A.2, 2.MD.A.3, 2.MD.A.4, 2.MD.B.5, 2.MD.B.6, 3.MD.A.2, 4.MD.A.1, 4.MD.A.2, 5.MD.A.1",
"A_mixed-up_clock": "1.MD.B.3, 2.MD.C.7, 3.MD.A.1",
"Ladybird_count": "1.MD.C.4",
"Choosing_triangles": "1.G.A.1, 2.G.A.1",
"Coloring_triangles": "1.G.A.1, 2.G.A.1",
"Matching_triangles": "1.G.A.1, 2.G.A.1",
"Four_triangles_puzzle": "1.G.A.2",
"Hex": "1.G.A.2",
"Tangram_tangle": "1.G.A.2",
"Tangrams": "1.G.A.2",
"Happy_halving": "1.G.A.3, 2.G.A.3, 4.G.A.3",
"Ladybirds_in_the_garden": "2.OA.C.3",
"Asn_numbers": "2.OA.C.3, 3.OA.D.9",
"Pemdas_puzzle": "5.OA.A.1, 5.OA.A.2",
"asn_numbers_(medium)": "2.OA.C.3, 3.OA.D.9",
"Swimming_pool_tiles": "2.OA.C.4",
"Ranking_addition": "2.NBT.B.6, 2.NBT.B.7, NBT.B.8",
"Addition_shuffle": "2.NBT.B.6, 2.NBT.B.7, NBT.B.8, 4.NBT.B.4",
"I'm_eight": "2.NBT.B.9",
"Changing_50_cents": "2.MD.C.8",
"Data_duos": "2.MD.D.9",
"Data_table": "2.MD.D.10, 3.MD.B.3, 3.MD.B.4, 4.MD.B.4, 5.MD.B.2",
"Square_patterns": "2.G.A.2",
"Mental_arithmetic": "3.OA.A.1, 3.OA.A.2, 3.OA.A.3, 3.OA.A.4",
"Numbers_and_shapes": "3.OA.A.1, 3.OA.A.2, 3.OA.A.3, 3.OA.A.4",
"Lots_of_lollies": "3.OA.B.5, 3.OA.B.6, 3.OA.D.8",
"Factor-multiple_chains": "3.OA.B.5, 3.OA.B.6",
"Multiplication_swap": "3.OA.C.7, 3.NBT.A.1, 4.NBT.B.5, 4.NBT.B.6, 5.NBT.B.5",
"Addition_swap": "3.NBT.A.1, 4.NBT.B.4",
"Ranking_multiplication": "3.NBT.A.2, 3.NBT.A.3",
"Rod_fractions": "3.NF.A.1, 3.NF.A.2, 3.NF.A.3, 4.NF.A.1, 4.NF.A.2, 4.NF.B.3, 4.NF.B.4, 4.NF.C.5, 4.NF.C.6, 4.NF.C.7, 5.NF.A.1, 5.NF.A.2, 5.NF.B.3, 5.NF.B.4, 5.NF.B.6, 5.NF.B.7",
"Fraction_lengths": "3.NF.A.1, 3.NF.A.2, 3.NF.A.3, 4.NF.A.1, 4.NF.A.2, 4.NF.B.3, 4.NF.B.4, 4.NF.C.5, 4.NF.C.6, 4.NF.C.7, 5.NF.A.1, 5.NF.A.2, 5.NF.B.3, 5.NF.B.4, 5.NF.B.6, 5.NF.B.7",
"Area_calculation": "3.MD.C.5, 3.MD.C.6, 3.MD.C.7, 4.MD.A.3",
"Area_comparison": "3.MD.C.5, 3.MD.C.6, 3.MD.C.7, 4.MD.A.3",
"Maximizing_area": "3.MD.D.8, 4.MD.A.3",
"Choosing_quadrilaterals": "3.G.A.1",
"Sorting_logic_blocks": "3.G.A.1, 5.G.B.3, 5.G.B.4",
"Area_fractions": "3.G.A.2",
"Paper_halving": "3.G.A.2",
"asn_numbers_(medium)": "4.OA.A.1",
"Mystery_matrix": "4.OA.A.1, 4.OA.A.2, 4.OA.A.3",
"Shape_times_shape": "4.OA.A.2, 4.OA.A.3",
"Super_shapes": "4.OA.A.2, 4.OA.A.3",
"Counting_cogs": "4.OA.B.4",
"Factors and Multiples": "4.OA.B.4",
"Robot_stepper": "4.OA.B.4",
"Visual_patterns": "4.OA.C.5, 5.OA.B.3",
"Multiplying_methods": "4.NBT.A.1, 4.NBT.A.2, 4.NBT.A.3, 5.NBT.A.1, 5.NBT.A.2, 5.NBT.A.3, 5.NBT.A.4",
"Heron's_formula": "4.MD.C.5, 4.MD.C.6, 4.MD.C.7, 4.G.A.1, 4.G.A.2",
"Three_squares": "4.MD.C.5, 4.MD.C.6, 4.MD.C.7, 4.G.A.1, 4.G.A.2",
"Trap_the_zoid": "4.G.A.2",
"Crazy_cut": "4.G.A.3",
"Groups_of_pennies": "5.NBT.B.6, 5.NBT.B.7",
"What's_in_the_box?": "5.NF.B.5",
"Tiling": "5.NF.B.5",
"asn_shapes_(medium)": "5.MD.C.3, 5.MD.C.4, 5.MD.C.5",
"A_cartesian_puzzle": "5.G.A.1, 5.G.A.2",
"Shape_riddle": "5.G.B.3, 5.G.B.4",
"Name_that_triangle": "5.G.B.3, 5.G.B.4",
}
