# Generated by Django 4.0.5 on 2022-07-20 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0002_profile_picture_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='usertype',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
