# Generated by Django 4.0.5 on 2022-07-20 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0003_profile_usertype'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='progress_dict',
            field=models.TextField(default='{}'),
        ),
    ]
