# Generated by Django 4.0.5 on 2022-07-23 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0005_alter_profile_picture_password_classroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_new_user',
            field=models.BooleanField(default=True),
        ),
    ]
