# Generated by Django 4.0.5 on 2022-08-08 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0006_profile_is_new_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='progress_dict',
            field=models.TextField(default='{"BCT": {"solveLevel": 0, "incorrectCount": 0}}'),
        ),
    ]
