# Generated by Django 4.0.5 on 2022-08-09 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0008_classroom_in_trash_classroom_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='name',
            field=models.CharField(default='Untitled Classroom', max_length=100),
        ),
    ]
