# Generated by Django 4.0.5 on 2022-08-13 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0009_alter_classroom_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='teacher_display_name',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
