# Generated by Django 3.2.9 on 2022-08-28 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0010_profile_teacher_display_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='owners',
            field=models.TextField(default='[]'),
        ),
    ]
