# Generated by Django 3.2.9 on 2022-11-10 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0012_profile_override_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cased_username',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
