# Generated by Django 3.1.4 on 2021-10-08 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzle', '0003_auto_20211007_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
