# Generated by Django 3.1.4 on 2021-11-22 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzle', '0011_auto_20211117_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='group_name',
            field=models.CharField(default='\ue83a', max_length=100),
        ),
    ]
