# Generated by Django 3.1.4 on 2021-11-24 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzle', '0015_auto_20211122_0716'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
    ]
