# Generated by Django 3.1.4 on 2021-11-24 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzle', '0016_resource_hidden'),
    ]

    operations = [
        migrations.AddField(
            model_name='tab',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
    ]
