# Generated by Django 3.2.9 on 2021-11-30 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzle', '0017_tab_hidden'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='category_name',
            field=models.CharField(default='zzzzz', max_length=100),
        ),
    ]
