# Generated by Django 3.2.9 on 2021-12-03 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzle', '0020_auto_20211201_0505'),
    ]

    operations = [
        migrations.AddField(
            model_name='standard',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
