# Generated by Django 3.2.9 on 2022-04-27 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzle', '0021_standard_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('resources', models.ManyToManyField(to='puzzle.Resource')),
            ],
        ),
    ]
