# Generated by Django 3.2.9 on 2022-06-03 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzle', '0023_auto_20220603_0809'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='length',
            field=models.IntegerField(default=2),
        ),
    ]
