# Generated by Django 3.2.9 on 2022-06-14 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzle', '0028_auto_20220607_0734'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaveList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tablist', models.TextField(default='[]')),
                ('fulllist', models.TextField(default='[]')),
            ],
        ),
    ]
