# Generated by Django 3.2.9 on 2022-12-02 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzle', '0030_savelist_full_couplet_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='group_name',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='resource',
            name='name',
            field=models.CharField(default='', max_length=150),
        ),
    ]
